//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosPrueba.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SegurosPruebaEntities : DbContext
    {
        public SegurosPruebaEntities()
            : base("name=SegurosPruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Asesor> tbl_Asesor { get; set; }
        public virtual DbSet<tbl_Cliente> tbl_Cliente { get; set; }
        public virtual DbSet<tbl_Compania> tbl_Compania { get; set; }
        public virtual DbSet<tbl_Producto> tbl_Producto { get; set; }
        public virtual DbSet<tbl_Venta> tbl_Venta { get; set; }
    }
}
