--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.5.327.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 29/12/2018 7:55:47 p. m.
-- Server version: 14.00.1000
--



USE SegurosPrueba
GO

IF DB_NAME() <> N'SegurosPrueba' SET NOEXEC ON
GO

--
-- Create table [dbo].[tbl_Producto]
--
PRINT (N'Create table [dbo].[tbl_Producto]')
GO
CREATE TABLE dbo.tbl_Producto (
  id_producto int IDENTITY,
  nombre_producto varchar(250) NOT NULL,
  prima numeric(18, 2) NOT NULL,
  cobertura varchar(250) NULL,
  asistencia varchar(250) NULL,
  id_compania int NOT NULL,
  CONSTRAINT PK_tbl_Producto_id_producto PRIMARY KEY CLUSTERED (id_producto)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[tbl_Compania]
--
PRINT (N'Create table [dbo].[tbl_Compania]')
GO
CREATE TABLE dbo.tbl_Compania (
  id_compania int IDENTITY,
  nombre_compania varchar(250) NOT NULL,
  CONSTRAINT PK_tbl_Compania_id_compania PRIMARY KEY CLUSTERED (id_compania)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[tbl_Cliente]
--
PRINT (N'Create table [dbo].[tbl_Cliente]')
GO
CREATE TABLE dbo.tbl_Cliente (
  id_cliente int IDENTITY,
  nombre_cliente varchar(250) NOT NULL,
  apellido_cliente varchar(250) NOT NULL,
  cedula_cliente varchar(50) NOT NULL,
  telefono_cliente varchar(50) NULL,
  direccion_cliente varchar(150) NULL,
  CONSTRAINT PK_tbl_Cliente_id_cliente PRIMARY KEY CLUSTERED (id_cliente)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[tbl_Asesor]
--
PRINT (N'Create table [dbo].[tbl_Asesor]')
GO
CREATE TABLE dbo.tbl_Asesor (
  id_asesor int IDENTITY,
  nombre_asesor varchar(250) NOT NULL,
  CONSTRAINT PK_tbl_Asesores_id_asesor PRIMARY KEY CLUSTERED (id_asesor)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[tbl_Venta]
--
PRINT (N'Create table [dbo].[tbl_Venta]')
GO
CREATE TABLE dbo.tbl_Venta (
  id_venta int IDENTITY,
  id_asesor int NOT NULL,
  id_cliente int NOT NULL,
  id_producto int NOT NULL,
  fecha datetime NOT NULL,
  CONSTRAINT PK_tbl_Venta_id_venta PRIMARY KEY CLUSTERED (id_venta)
)
ON [PRIMARY]
GO
-- 
-- Dumping data for table tbl_Asesor
--
SET IDENTITY_INSERT dbo.tbl_Asesor ON
GO
INSERT dbo.tbl_Asesor(id_asesor, nombre_asesor) VALUES (1, N'asesor numero 1')
GO
SET IDENTITY_INSERT dbo.tbl_Asesor OFF
GO
-- 
-- Dumping data for table tbl_Cliente
--
SET IDENTITY_INSERT dbo.tbl_Cliente ON
GO
INSERT dbo.tbl_Cliente(id_cliente, nombre_cliente, apellido_cliente, cedula_cliente, telefono_cliente, direccion_cliente) VALUES (1, N'pablo', N'perez', N'11122222', N'343434', N'')
GO
SET IDENTITY_INSERT dbo.tbl_Cliente OFF
GO
-- 
-- Dumping data for table tbl_Compania
--
SET IDENTITY_INSERT dbo.tbl_Compania ON
GO
INSERT dbo.tbl_Compania(id_compania, nombre_compania) VALUES (2, N'nueva primera')
INSERT dbo.tbl_Compania(id_compania, nombre_compania) VALUES (3, N'nueva dos')
GO
SET IDENTITY_INSERT dbo.tbl_Compania OFF
GO
-- 
-- Dumping data for table tbl_Producto
--
SET IDENTITY_INSERT dbo.tbl_Producto ON
GO
INSERT dbo.tbl_Producto(id_producto, nombre_producto, prima, cobertura, asistencia, id_compania) VALUES (1, N'nuevo product 1', 23123.00, N'nueva 1111', N'fff', 2)
INSERT dbo.tbl_Producto(id_producto, nombre_producto, prima, cobertura, asistencia, id_compania) VALUES (2, N'nuevo prod 2', 11111111.00, N'nnn', N'nnn', 3)
GO
SET IDENTITY_INSERT dbo.tbl_Producto OFF
GO
-- 
-- Dumping data for table tbl_Venta
--
SET IDENTITY_INSERT dbo.tbl_Venta ON
GO
INSERT dbo.tbl_Venta(id_venta, id_asesor, id_cliente, id_producto, fecha) VALUES (1, 1, 1, 1, '2018-12-29 12:49:51.963')
INSERT dbo.tbl_Venta(id_venta, id_asesor, id_cliente, id_producto, fecha) VALUES (2, 1, 1, 2, '2018-12-29 12:50:08.393')
INSERT dbo.tbl_Venta(id_venta, id_asesor, id_cliente, id_producto, fecha) VALUES (3, 1, 1, 1, '2018-12-29 12:51:54.830')
GO
SET IDENTITY_INSERT dbo.tbl_Venta OFF
GO

USE SegurosPrueba
GO

IF DB_NAME() <> N'SegurosPrueba' SET NOEXEC ON
GO

--
-- Create foreign key [FK_tbl_Producto_id_compania] on table [dbo].[tbl_Producto]
--
PRINT (N'Create foreign key [FK_tbl_Producto_id_compania] on table [dbo].[tbl_Producto]')
GO
ALTER TABLE dbo.tbl_Producto
  ADD CONSTRAINT FK_tbl_Producto_id_compania FOREIGN KEY (id_compania) REFERENCES dbo.tbl_Compania (id_compania)
GO

--
-- Create foreign key [FK_tbl_Venta_id_asesor] on table [dbo].[tbl_Venta]
--
PRINT (N'Create foreign key [FK_tbl_Venta_id_asesor] on table [dbo].[tbl_Venta]')
GO
ALTER TABLE dbo.tbl_Venta
  ADD CONSTRAINT FK_tbl_Venta_id_asesor FOREIGN KEY (id_asesor) REFERENCES dbo.tbl_Asesor (id_asesor)
GO

--
-- Create foreign key [FK_tbl_Venta_id_cliente] on table [dbo].[tbl_Venta]
--
PRINT (N'Create foreign key [FK_tbl_Venta_id_cliente] on table [dbo].[tbl_Venta]')
GO
ALTER TABLE dbo.tbl_Venta
  ADD CONSTRAINT FK_tbl_Venta_id_cliente FOREIGN KEY (id_cliente) REFERENCES dbo.tbl_Cliente (id_cliente)
GO

--
-- Create foreign key [FK_tbl_Venta_id_producto] on table [dbo].[tbl_Venta]
--
PRINT (N'Create foreign key [FK_tbl_Venta_id_producto] on table [dbo].[tbl_Venta]')
GO
ALTER TABLE dbo.tbl_Venta
  ADD CONSTRAINT FK_tbl_Venta_id_producto FOREIGN KEY (id_producto) REFERENCES dbo.tbl_Producto (id_producto)
GO
SET NOEXEC OFF
GO